title: Patrick Radner
description: > # this means to ignore newlines until "baseurl:"
  [TBD]
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Patrick Radner # add your name
author-img: david-freeman.jpg # add your photo
about-author: Computer scientist and games engineer intrested in neural rendering, deep learning, GANs, RL.
 # add description
social-twitter: twitter.com/patrick_radner
social-facebook: # add your Facebook handle
social-github: github.com/Mirjang
social-linkedin: www.linkedin.com/in/patrick-radner-9179721a7
social-email: mailto:radner.patrick@gmail.com


# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
